language: node_js
node_js:
  - '10.13.1'

cache:
  directories:
    - ~/.npm
    - 'node_modules'

notifications:
  email: false

install:
  - npm ci
  - npm i --no-save codecov

script:
  - npm run lint
  - npm run test -- --code-coverage --watch=false
  - npm run build

after_success:
  - npm run codecov
